jwt:
  secretKey: adkjfnhakjdfnjek1234235jakdsbfajk12kjdsnfq2knkldsdfasd

spring:
  application:
    name: api-gateway

  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                -isEnabled: true
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Anuj
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka